services:
  whanjeab-line:
    container_name: whanjeab-line
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgresql://play2:123456@db:5432/whanjeabdb?schema=public
      - PORT=3016
    command: sh -c "npx prisma generate && npm start"
    ports:
      - "3016:3001"
    networks:
      - dev_network

networks:
  dev_network:
    external: true