services:
  whanjeab-line:
    container_name: whanjeab-line
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgresql://play2:123456@db:5432/whanjeabdb?schema=public
      - PORT=3015
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm start"
    ports:
      - "3015:3001"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dev_network

networks:
  dev_network:
    external: true


volumes:
  db_data: